spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123456
    connection-timeout: 100ms
    template:
      retry:
        enabled: true
        # 初始重试间隔时间，当multiplier=2时，第一次重试间隔时间为1s，第二次为2s，第三次为4s，第四次为8s
        multiplier: 2
        initial-interval: 1s
        max-attempts: 3
    # 生产者确认机制 none 关闭； simple 等待确认，阻塞操作； correlated 异步确认
    publisher-confirm-type: correlated
    # 开启return机制，当消息无法路由到队列时，会将消息失败信息返回给生产者
    publisher-returns: true